services:
  lunotel-next:
    container_name: lunotel-next
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    working_dir: /usr/src/lunotel-next
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env.vps

    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - monorepo-network
networks:
  monorepo-network:
    external: true
