
FROM node:20.16.0-alpine
WORKDIR /usr/src/lunotel-next
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 600000
COPY . .

ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET
ARG LUNOTEL_API_GRAPHQL_URL
ARG REACT_APP_API_GRAPHQL_URL
ARG REACT_APP_API_URL
ARG REACT_APP_API_WS
ARG KAKAO_JAVASCRIPT_KEY_MAP
ARG NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY_MAP

ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV LUNOTEL_API_GRAPHQL_URL=$LUNOTEL_API_GRAPHQL_URL
ENV REACT_APP_API_GRAPHQL_URL=$REACT_APP_API_GRAPHQL_URL
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_API_WS=$REACT_APP_API_WS
ENV KAKAO_JAVASCRIPT_KEY_MAP=$KAKAO_JAVASCRIPT_KEY_MAP
ENV NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY_MAP=$NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY_MAP

RUN yarn build
EXPOSE 3000
CMD ["yarn", "start"]
