services:
  lunotel-next:
    container_name: lunotel-next
    image: node:20.16.0
    restart: always

    ports:
      - '3000:3000'

    working_dir: /usr/src/lunotel-next
    volumes:
      - ./:/usr/src/lunotel-next
      - /usr/src/lunotel-next/node_modules

    environment:
      - PORT=3000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=8f3a1c9d2e4b7a6c9f0d1e2a3b4c5d6e
      - LUNOTEL_API_GRAPHQL_URL=http://lunotel-api:3001/graphql
      - REACT_APP_API_GRAPHQL_URL=http://localhost:5001/graphql
    dns:
      - 8.8.8.8
      - 1.1.1.1

    networks:
      - monorepo-network

    command: sh -c "yarn install && yarn build && yarn start"

networks:
  monorepo-network:
    external: true
