export enum PropertyType {
	MOTEL = 'MOTEL',
	HOTEL = 'HOTEL',
	PENSION = 'PENSION',
	POLL_VILLA = 'POLL_VILLA',
	CAMPING = 'CAMPING',
	GLAMPING = 'GLAMPING',
}

export enum PropertyTypeKorean {
	ALL = '천제',
	MOTEL = '모텔',
	HOTEL = '호텔',
	PENSION = '펜션',
	POLL_VILLA = '풀빌라',
	CAMPING = '캠핑',
	글램핑 = '글램핑',
}

export enum PropertyStatus {
	DRAFT = 'DRAFT',
	ACTIVE = 'ACTIVE',
	INACTIVE = 'INACTIVE',
	BLOCKED = 'BLOCKED',
	DELETE = 'DELETE',
}

export enum PropertyLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
	GANGNEUNG = 'GANGNEUNG',
	SOKCHO = 'SOKCHO',
	YEOSU = 'YEOSU',
	HEUNDE = 'HEUNDE',
	GAPYEONG = 'GAPYEONG',
}

export enum PropertyLocationKorean {
	SEOUL = '서울',
	BUSAN = '부산',
	INCHEON = '인천',
	DAEGU = '대구',
	GYEONGJU = '광주',
	GWANGJU = '경주',
	CHONJU = '청주',
	DAEJON = '대전',
	JEJU = '제주',
	GANGNEUNG = '강릉',
	SOKCHO = '속초',
	YEOSU = '여수',
	HEUNDE = '해운대',
	GAPYEONG = '가평',
}

export enum PropertyAmenity {
	SAUNA = 'SAUNA',
	SWIMMING_POOL = 'SWIMMING_POOL',
	BARBECUE = 'BARBECUE',
	RESTAURANT = 'RESTAURANT',
	FINTESS = 'FINTESS',
	WATER_PARK = 'WATER_PARK',
	STALL = 'STALL',
	KITCHEN = 'KITCHEN',
	DRYER = 'DRYER',
	DEHYDRATOR = 'DEHYDRATOR',
	WIFI = 'WIFI',
	NON_SMOKING = 'NON_SMOKING',
	TV = 'TV',
	CONDITIONER = 'AIR_CONDITIONER',
	SHOWER_ROOM = 'SHOWER_ROOM',
	FREE_PARKING = 'FREE_PARKING',
	COFFEE_MACHINE = 'COFFEE_MACHINE',
	PARKING = 'PARKING',
	ELEVATOR = 'ELEVATOR',
	SPA = 'SPA',
	TWIN_BED = 'TWIN_BED',
	KARAOKE = 'KARAOKE',
	COUPLE_PC = 'COUPLE_PC',
	GAMING_PC = 'GAMING_PC',
}

export enum PropertyOtherAmenity {
	BREAKFAST_PROVIDED = 'BREAKFAST PROVIDED',
	FREE_PARKING = 'FREE PARKING',
	PETS_ALLOWED = 'PETS ALLOWED',
	SAUNA_JJIMJILBANG = 'SAUNA/JJIMJILBANG',
	IN_ROOM_COOKING = 'IN-ROOM COOKING',
	PICK_UP_SERVICE = 'PICK-UP SERVICE',
	SMOKING_ALLOWED = 'SMOKING ALLOWED',
	LUGGAGE_STORAGE = 'LUGGAGE STORAGE AVAILABLE',
}
